In [1]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.utils import np_utils
import tensorflow as tf

In [2]:
import numpy
numpy.random.seed(7)
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
char_to_int = dict((c, i) for i, c in enumerate(alphabet))
int_to_char = dict((i, c) for i, c in enumerate(alphabet))

In [3]:
char_to_int

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11,
 'M': 12,
 'N': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}

In [4]:
int_to_char

{0: 'A',
 1: 'B',
 2: 'C',
 3: 'D',
 4: 'E',
 5: 'F',
 6: 'G',
 7: 'H',
 8: 'I',
 9: 'J',
 10: 'K',
 11: 'L',
 12: 'M',
 13: 'N',
 14: 'O',
 15: 'P',
 16: 'Q',
 17: 'R',
 18: 'S',
 19: 'T',
 20: 'U',
 21: 'V',
 22: 'W',
 23: 'X',
 24: 'Y',
 25: 'Z'}

In [5]:
seq_length = 1
dataX = []
dataY = []

In [6]:
type(dataX)

list

In [7]:
for i in range(0, len(alphabet) - seq_length, 1):
  seq_in = alphabet[i:i + seq_length]
  seq_out = alphabet[i + seq_length ]
  dataX.append([char_to_int[char] for char in seq_in])
  dataY.append(char_to_int[seq_out])
  print(seq_in, '->', seq_out)

A -> B
B -> C
C -> D
D -> E
E -> F
F -> G
G -> H
H -> I
I -> J
J -> K
K -> L
L -> M
M -> N
N -> O
O -> P
P -> Q
Q -> R
R -> S
S -> T
T -> U
U -> V
V -> W
W -> X
X -> Y
Y -> Z


In [8]:
X = numpy.reshape(dataX, (len(dataX), seq_length, 1))
X.shape

(25, 1, 1)

In [9]:
X = X / float(len(alphabet))
y = tf.keras.utils.to_categorical(dataY)

In [10]:
y[0]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [11]:
y.shape

(25, 26)

In [12]:
model = Sequential()
model.add(LSTM(32, input_shape=(X.shape[1], X.shape[2])))
model.add(Dense(y.shape[1], activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=500, batch_size=1, verbose=2)

Epoch 1/500
25/25 - 2s - loss: 3.2653 - accuracy: 0.0000e+00
Epoch 2/500
25/25 - 0s - loss: 3.2577 - accuracy: 0.0400
Epoch 3/500
25/25 - 0s - loss: 3.2549 - accuracy: 0.0000e+00
Epoch 4/500
25/25 - 0s - loss: 3.2520 - accuracy: 0.0000e+00
Epoch 5/500
25/25 - 0s - loss: 3.2495 - accuracy: 0.0000e+00
Epoch 6/500
25/25 - 0s - loss: 3.2467 - accuracy: 0.0400
Epoch 7/500
25/25 - 0s - loss: 3.2439 - accuracy: 0.0000e+00
Epoch 8/500
25/25 - 0s - loss: 3.2412 - accuracy: 0.0400
Epoch 9/500
25/25 - 0s - loss: 3.2379 - accuracy: 0.0400
Epoch 10/500
25/25 - 0s - loss: 3.2347 - accuracy: 0.0400
Epoch 11/500
25/25 - 0s - loss: 3.2320 - accuracy: 0.0000e+00
Epoch 12/500
25/25 - 0s - loss: 3.2280 - accuracy: 0.0400
Epoch 13/500
25/25 - 0s - loss: 3.2246 - accuracy: 0.0000e+00
Epoch 14/500
25/25 - 0s - loss: 3.2210 - accuracy: 0.0000e+00
Epoch 15/500
25/25 - 0s - loss: 3.2166 - accuracy: 0.0000e+00
Epoch 16/500
25/25 - 0s - loss: 3.2123 - accuracy: 0.0000e+00
Epoch 17/500
25/25 - 0s - loss: 3.2077 - 

In [13]:
#!pip install numpy==1.19

In [14]:
scores = model.evaluate(X, y, verbose=0)
print('Model Accuracy: %.2f%%'%(scores[1]*100))

Model Accuracy: 84.00%


In [15]:
dataX[4]

[4]

In [16]:
test = dataX[4]
test = numpy.reshape(test, (1, len(test), 1))
test = test / float(len(alphabet))
pred = model.predict(test, verbose=0)
pred

array([[1.3033396e-07, 2.5034326e-03, 3.6452860e-02, 1.2889123e-01,
        2.0545088e-01, 2.1998926e-01, 1.7860064e-01, 1.1631389e-01,
        6.4117678e-02, 2.9297944e-02, 1.1435395e-02, 4.4179508e-03,
        1.6767395e-03, 5.6538824e-04, 2.0109670e-04, 6.2089908e-05,
        1.6502521e-05, 5.0657441e-06, 1.4308932e-06, 3.4542191e-07,
        1.0925969e-07, 2.0923492e-08, 5.6077938e-09, 9.1541047e-10,
        1.8981759e-10, 5.7268502e-11]], dtype=float32)

In [17]:
ind = numpy.argmax(pred)
res = int_to_char[ind]
res

'F'

In [18]:
for pattern in dataX:
  X = numpy.reshape(pattern, (1, len(pattern), 1))
  x = X / float(len(alphabet))
  prediction = model.predict(x, verbose=0)
  index = numpy.argmax(prediction)
  result = int_to_char[index]
  seq_in = [int_to_char[value] for value in pattern]
  print(seq_in, '-->', result)

['A'] --> B
['B'] --> B
['C'] --> D
['D'] --> E
['E'] --> F
['F'] --> G
['G'] --> H
['H'] --> I
['I'] --> J
['J'] --> K
['K'] --> L
['L'] --> M
['M'] --> N
['N'] --> O
['O'] --> P
['P'] --> Q
['Q'] --> R
['R'] --> S
['S'] --> T
['T'] --> U
['U'] --> V
['V'] --> X
['W'] --> Z
['X'] --> Z
['Y'] --> Z


In [19]:
# LSTM to lern three-char time step to one-char mapping
import numpy
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.utils import np_utils
import tensorflow as tf
numpy.random.seed(7)
alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

char_to_int = dict((c, i) for i, c in enumerate(alphabet))
int_to_char = dict((i, c) for i, c in enumerate(alphabet))

seq_length = 3
dataX = []
dataY = []
for i in range(0, len(alphabet) - seq_length, 1):
  seq_in = alphabet[i:i + seq_length]
  seq_out = alphabet[i + seq_length ]
  dataX.append([char_to_int[char] for char in seq_in])
  dataY.append(char_to_int[seq_out])
  print(seq_in, '->', seq_out)

X = numpy.reshape(dataX, (len(dataX), seq_length, 1))

ABC -> D
BCD -> E
CDE -> F
DEF -> G
EFG -> H
FGH -> I
GHI -> J
HIJ -> K
IJK -> L
JKL -> M
KLM -> N
LMN -> O
MNO -> P
NOP -> Q
OPQ -> R
PQR -> S
QRS -> T
RST -> U
STU -> V
TUV -> W
UVW -> X
VWX -> Y
WXY -> Z


In [20]:
X

array([[[ 0],
        [ 1],
        [ 2]],

       [[ 1],
        [ 2],
        [ 3]],

       [[ 2],
        [ 3],
        [ 4]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 5],
        [ 6],
        [ 7]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 7],
        [ 8],
        [ 9]],

       [[ 8],
        [ 9],
        [10]],

       [[ 9],
        [10],
        [11]],

       [[10],
        [11],
        [12]],

       [[11],
        [12],
        [13]],

       [[12],
        [13],
        [14]],

       [[13],
        [14],
        [15]],

       [[14],
        [15],
        [16]],

       [[15],
        [16],
        [17]],

       [[16],
        [17],
        [18]],

       [[17],
        [18],
        [19]],

       [[18],
        [19],
        [20]],

       [[19],
        [20],
        [21]],

       [[20],
        [21],
        [22]],

       [[21],
        [22],
        [23]],

       [[22],
        [23],
    

In [21]:
X.shape

(23, 3, 1)

In [22]:
X = X / float(len(alphabet))
y = tf.keras.utils.to_categorical(dataY)
model = Sequential()
model.add(LSTM(32, input_shape=(X.shape[1], X.shape[2])))
model.add(Dense(y.shape[1], activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=500, batch_size=1, verbose=2)
scores = model.evaluate(X, y, verbose=0)
print('Model Accuracy: %.2f%%'%(scores[1]*100))

for pattern in dataX:
  x = numpy.reshape(pattern, (1, len(pattern), 1))
  x = X / float(len(alphabet))
  prediction = model.predict(x, verbose=0)
  index = numpy.argmax(prediction)
  result = int_to_char[index]
  seq_in = [int_to_char[value] for value in pattern]
  print(seq_in, '-->', result)

Epoch 1/500
23/23 - 2s - loss: 3.2634 - accuracy: 0.0000e+00
Epoch 2/500
23/23 - 0s - loss: 3.2500 - accuracy: 0.0435
Epoch 3/500
23/23 - 0s - loss: 3.2414 - accuracy: 0.0435
Epoch 4/500
23/23 - 0s - loss: 3.2331 - accuracy: 0.0435
Epoch 5/500
23/23 - 0s - loss: 3.2246 - accuracy: 0.0435
Epoch 6/500
23/23 - 0s - loss: 3.2156 - accuracy: 0.0000e+00
Epoch 7/500
23/23 - 0s - loss: 3.2055 - accuracy: 0.0435
Epoch 8/500
23/23 - 0s - loss: 3.1942 - accuracy: 0.0000e+00
Epoch 9/500
23/23 - 0s - loss: 3.1827 - accuracy: 0.0435
Epoch 10/500
23/23 - 0s - loss: 3.1681 - accuracy: 0.0435
Epoch 11/500
23/23 - 0s - loss: 3.1537 - accuracy: 0.0435
Epoch 12/500
23/23 - 0s - loss: 3.1368 - accuracy: 0.0435
Epoch 13/500
23/23 - 0s - loss: 3.1211 - accuracy: 0.0000e+00
Epoch 14/500
23/23 - 0s - loss: 3.1029 - accuracy: 0.0435
Epoch 15/500
23/23 - 0s - loss: 3.0859 - accuracy: 0.0435
Epoch 16/500
23/23 - 0s - loss: 3.0688 - accuracy: 0.0435
Epoch 17/500
23/23 - 0s - loss: 3.0520 - accuracy: 0.0435
Epoch 1

In [23]:
model.fit(X, y, epochs=5000, batch_size=len(dataX), verbose=2, shuffle = False)

Streaming output truncated to the last 5000 lines.
Epoch 2501/5000
1/1 - 0s - loss: 0.2048 - accuracy: 1.0000
Epoch 2502/5000
1/1 - 0s - loss: 0.2048 - accuracy: 1.0000
Epoch 2503/5000
1/1 - 0s - loss: 0.2047 - accuracy: 1.0000
Epoch 2504/5000
1/1 - 0s - loss: 0.2046 - accuracy: 1.0000
Epoch 2505/5000
1/1 - 0s - loss: 0.2046 - accuracy: 1.0000
Epoch 2506/5000
1/1 - 0s - loss: 0.2045 - accuracy: 1.0000
Epoch 2507/5000
1/1 - 0s - loss: 0.2045 - accuracy: 1.0000
Epoch 2508/5000
1/1 - 0s - loss: 0.2044 - accuracy: 1.0000
Epoch 2509/5000
1/1 - 0s - loss: 0.2044 - accuracy: 1.0000
Epoch 2510/5000
1/1 - 0s - loss: 0.2043 - accuracy: 1.0000
Epoch 2511/5000
1/1 - 0s - loss: 0.2042 - accuracy: 1.0000
Epoch 2512/5000
1/1 - 0s - loss: 0.2042 - accuracy: 1.0000
Epoch 2513/5000
1/1 - 0s - loss: 0.2041 - accuracy: 1.0000
Epoch 2514/5000
1/1 - 0s - loss: 0.2041 - accuracy: 1.0000
Epoch 2515/5000
1/1 - 0s - loss: 0.2040 - accuracy: 1.0000
Epoch 2516/5000
1/1 - 0s - loss: 0.2040 - accuracy: 1.0000
Epoch

In [24]:
print('Test a random pattern : ')
for i in range(0, 20):
  pattern_index = numpy.random.randint(len(dataX))
  pattern = dataX[pattern_index]
  x = numpy.reshape(pattern, (1, len(pattern), 1))
  x = x / float(len(alphabet))
  prediction = model.predict(x, verbose=0)
  index = numpy.argmax(prediction)
  result = int_to_char[index]
  seq_in = [int_to_char[value] for value in pattern]
  print(seq_in, '-->', result)

Test a random pattern : 
['P', 'Q', 'R'] --> S
['E', 'F', 'G'] --> H
['W', 'X', 'Y'] --> Z
['D', 'E', 'F'] --> G
['T', 'U', 'V'] --> W
['H', 'I', 'J'] --> K
['O', 'P', 'Q'] --> R
['I', 'J', 'K'] --> L
['O', 'P', 'Q'] --> R
['K', 'L', 'M'] --> N
['I', 'J', 'K'] --> L
['H', 'I', 'J'] --> K
['G', 'H', 'I'] --> J
['E', 'F', 'G'] --> H
['Q', 'R', 'S'] --> T
['H', 'I', 'J'] --> K
['M', 'N', 'O'] --> P
['A', 'B', 'C'] --> D
['L', 'M', 'N'] --> O
['G', 'H', 'I'] --> J


In [25]:
import numpy
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.utils import np_utils
from keras.preprocessing.sequence import pad_sequences
import tensorflow as tf

In [26]:
numpy.random.seed(7)
alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

char_to_int = dict((c, i) for i, c in enumerate(alphabet))
int_to_char = dict((i, c) for i, c in enumerate(alphabet))

num_inputs = 1000
max_len = 5
dataX = []
dataY = []

In [27]:
for i in range(num_inputs):
  start = numpy.random.randint(len(alphabet)-2)
  end = numpy.random.randint(start, min(start+max_len, len(alphabet)-1))
  sequence_in = alphabet[start:end+1]
  sequence_out = alphabet[end+1]
  dataX.append([char_to_int[char] for char in sequence_in])
  dataY.append(char_to_int[sequence_out])
  print(sequence_in, '-->', sequence_out)

X = pad_sequences(dataX, maxlen = max_len, dtype='float32')
X = numpy.reshape(X, (X.shape[0], max_len, 1))
X = X / float(len(alphabet))
y = tf.keras.utils.to_categorical(dataY)

PQRST --> U
W --> X
O --> P
OPQ --> R
IJKLM --> N
QRSTU --> V
ABCD --> E
X --> Y
GHIJ --> K
M --> N
XY --> Z
QRST --> U
ABC --> D
JKLMN --> O
OP --> Q
XY --> Z
D --> E
T --> U
B --> C
QRSTU --> V
HIJ --> K
JKLM --> N
ABCDE --> F
X --> Y
V --> W
DE --> F
DEFG --> H
BCDE --> F
EFGH --> I
BCDE --> F
FG --> H
RST --> U
TUV --> W
STUV --> W
LMN --> O
P --> Q
MNOP --> Q
JK --> L
MNOP --> Q
OPQRS --> T
UVWXY --> Z
PQRS --> T
D --> E
EFGH --> I
IJK --> L
WX --> Y
STUV --> W
MNOPQ --> R
P --> Q
WXY --> Z
VWX --> Y
V --> W
HI --> J
KLMNO --> P
UV --> W
JKL --> M
ABCDE --> F
WXY --> Z
M --> N
CDEF --> G
KLMNO --> P
RST --> U
RS --> T
W --> X
J --> K
WX --> Y
JKLMN --> O
MN --> O
L --> M
BCDE --> F
TU --> V
MNOPQ --> R
NOPQR --> S
HIJ --> K
JKLM --> N
STUVW --> X
QRST --> U
N --> O
VWXY --> Z
B --> C
UVWX --> Y
OP --> Q
K --> L
C --> D
X --> Y
ST --> U
JKLM --> N
B --> C
QR --> S
RS --> T
VWXY --> Z
S --> T
NOP --> Q
KLMNO --> P
IJ --> K
EF --> G
MNOP --> Q
WXY --> Z
HI --> J
P --> Q
STUVW --> X
Q

In [28]:

batch_size = 1
model = Sequential()
model.add(LSTM(32, input_shape=(X.shape[1],1)))
model.add(Dense(y.shape[1], activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=500, batch_size=1, verbose=2)

Epoch 1/500
1000/1000 - 3s - loss: 3.1018 - accuracy: 0.0690
Epoch 2/500
1000/1000 - 2s - loss: 2.8342 - accuracy: 0.1050
Epoch 3/500
1000/1000 - 2s - loss: 2.5049 - accuracy: 0.1840
Epoch 4/500
1000/1000 - 2s - loss: 2.2529 - accuracy: 0.2450
Epoch 5/500
1000/1000 - 2s - loss: 2.0819 - accuracy: 0.2880
Epoch 6/500
1000/1000 - 2s - loss: 1.9523 - accuracy: 0.3450
Epoch 7/500
1000/1000 - 2s - loss: 1.8396 - accuracy: 0.3520
Epoch 8/500
1000/1000 - 2s - loss: 1.7429 - accuracy: 0.3910
Epoch 9/500
1000/1000 - 2s - loss: 1.6667 - accuracy: 0.4010
Epoch 10/500
1000/1000 - 2s - loss: 1.5899 - accuracy: 0.4570
Epoch 11/500
1000/1000 - 2s - loss: 1.5221 - accuracy: 0.4650
Epoch 12/500
1000/1000 - 2s - loss: 1.4592 - accuracy: 0.5000
Epoch 13/500
1000/1000 - 2s - loss: 1.3935 - accuracy: 0.5180
Epoch 14/500
1000/1000 - 2s - loss: 1.3489 - accuracy: 0.5210
Epoch 15/500
1000/1000 - 2s - loss: 1.2941 - accuracy: 0.5730
Epoch 16/500
1000/1000 - 2s - loss: 1.2487 - accuracy: 0.5830
Epoch 17/500
1000

In [29]:
scores = model.evaluate(X, y, verbose=0)
print('Model Accuracy: %.2f%%'%(scores[1]*100))

Model Accuracy: 98.60%


In [30]:
for i in range(20):
  pattern_index = numpy.random.randint(len(dataX))
  pattern = dataX[pattern_index]
  x = pad_sequences([pattern], maxlen= max_len, dtype='float32')
  x = numpy.reshape(x, (1, max_len, 1))
  x = x / float(len(alphabet))
  prediction = model.predict(x, verbose=0)
  index = numpy.argmax(prediction)
  result = int_to_char[index]
  seq_in = [int_to_char[value] for value in pattern]
  print(seq_in, '-->', result)

['J'] --> J
['H', 'I', 'J'] --> K
['E', 'F'] --> G
['K', 'L', 'M'] --> N
['B'] --> C
['C'] --> D
['R', 'S'] --> T
['A', 'B', 'C'] --> D
['C', 'D', 'E'] --> F
['N', 'O', 'P'] --> Q
['C', 'D'] --> E
['L', 'M'] --> N
['F', 'G', 'H', 'I', 'J'] --> K
['N', 'O', 'P', 'Q'] --> R
['C', 'D', 'E', 'F', 'G'] --> H
['A', 'B', 'C'] --> D
['R', 'S', 'T', 'U', 'V'] --> W
['B', 'C', 'D'] --> E
['F', 'G'] --> H
['K'] --> L
